services:
  streamlittest:
    build: .
    ports:
      - "8501:8501"
  searxngtest:
    image: searxng/searxng
    container_name: searxng
    volumes:
      - /e/Work/ai-search-engine/searxng/searxng:/etc/searxng
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=local-searxng
      - SEARXNG_OUTPUT_FORMAT=json