name: Build and Push Docker Image for Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Set up Environment Variables from Secrets
        run: |
          echo DEFAULT_GITHUB_TOKEN=${{ secrets.DEFAULT_GITHUB_TOKEN }} >> .env

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-llm-agent:${{ steps.tag_version.outputs.new_tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/web-llm-agent:${{ steps.tag_version.outputs.new_tag }}
